export const event = {
  name: 'Hacklonega',
  programName: 'Hacktoberfest Hack Day',
  location: 'Dahlonega, Georgia',
  hostName: 'University of North Georgia',
  siteUrl: 'https://hacklonega.dev/',
  description: 'Hacklonega is a free one-day student hackathon at the University of North Georgia in Dahlonega on October 24, 2026. Team up and build with open-source AI.',
  registrationUrl: 'https://events.mlh.com/events/14787-hacktoberfest-hack-day-dahlonega-x-university-of-north-georgia',
  conductUrl: 'https://static.mlh.io/docs/mlh-code-of-conduct.pdf',
  hostGuideUrl: 'https://hacktoberfest-handbook.mlh.com/',
  date: '2026-10-24',
  dateLabel: 'October 24',
  startingLocation: 'MCCB 109',
  time: null as string | null,
  venue: null as string | null,
  contactEmail: null as string | null,
  partnerChallenge: null as string | null,
} as const;
